This is makeindex, version 2.16 [MiKTeX 22.10].
Scanning style file ./requerimientos.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file requerimientos.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (12 comparisons).
Generating output file requerimientos.acr....done (11 lines written, 0 warnings).
Output written in requerimientos.acr.
Transcript written in requerimientos.alg.
